import 'dart:math';

/// Mini Sudoku — classic sudoku scaled down for a gentle start: 4×4 (2×2
/// boxes) on early levels, 6×6 (2×3 boxes) in the middle, full 9×9 later.
/// Boards are generated by filling a complete valid grid (seeded backtracking)
/// and then removing cells only while the solution stays unique — so every
/// puzzle has exactly one solution and is solvable by construction.
///
/// Pure Dart (no Flutter imports) so it stays unit-testable.

class MiniSudokuConfig {
  const MiniSudokuConfig({
    required this.size,
    required this.boxRows,
    required this.boxCols,
    required this.blanks,
  });

  final int size;
  final int boxRows; // rows per box
  final int boxCols; // cols per box
  final int blanks; // target number of cells to clear (may end up fewer)
}

MiniSudokuConfig miniSudokuConfigForLevel(int level) {
  if (level < 4) {
    return MiniSudokuConfig(
        size: 4, boxRows: 2, boxCols: 2, blanks: 5 + level); // 6..8 of 16
  }
  if (level < 10) {
    return MiniSudokuConfig(
        size: 6, boxRows: 2, boxCols: 3, blanks: 10 + level); // 14..19 of 36
  }
  return MiniSudokuConfig(
      size: 9,
      boxRows: 3,
      boxCols: 3,
      // Target only: the generator stops digging when removing more would cost
      // uniqueness, so a high target is safe and simply means "as hard as this
      // grid allows". The old ceiling of 52 was reached at level 13.
      blanks: (26 + 2 * level).clamp(26, 58)); // of 81
}

class SudokuCell {
  SudokuCell(this.solution, {required this.given});

  final int solution;
  final bool given;
  int? entered; // player's value (non-given cells)

  int? get effective => given ? solution : entered;
}

class MiniSudokuBoard {
  MiniSudokuBoard({
    required this.cells,
    required this.boxRows,
    required this.boxCols,
  });

  final List<List<SudokuCell>> cells;
  final int boxRows;
  final int boxCols;

  int get size => cells.length;

  bool get isSolved {
    for (final row in cells) {
      for (final cell in row) {
        if (cell.effective != cell.solution) return false;
      }
    }
    return true;
  }

  int get blankCount {
    var n = 0;
    for (final row in cells) {
      for (final cell in row) {
        if (!cell.given) n++;
      }
    }
    return n;
  }

  /// Whether the value at (r,c) clashes with another filled cell in its row,
  /// column, or box — used for gentle conflict highlighting.
  bool hasConflict(int r, int c) {
    final v = cells[r][c].effective;
    if (v == null) return false;
    for (var i = 0; i < size; i++) {
      if (i != c && cells[r][i].effective == v) return true;
      if (i != r && cells[i][c].effective == v) return true;
    }
    final br = (r ~/ boxRows) * boxRows, bc = (c ~/ boxCols) * boxCols;
    for (var i = br; i < br + boxRows; i++) {
      for (var j = bc; j < bc + boxCols; j++) {
        if ((i != r || j != c) && cells[i][j].effective == v) return true;
      }
    }
    return false;
  }

  /// Builds a board for [level], seeded so a retry gives the same puzzle.
  static MiniSudokuBoard generate(int level) {
    final cfg = miniSudokuConfigForLevel(level);
    final rng = Random(level * 4787 + 379);

    final solution = _fillGrid(cfg, rng)!; // backtracking always succeeds
    final givens = [
      for (final row in solution) [...row]
    ];

    // Dig blanks in random order, keeping the solution unique.
    final order = [
      for (var i = 0; i < cfg.size * cfg.size; i++) i
    ]..shuffle(rng);
    var removed = 0;
    for (final p in order) {
      if (removed == cfg.blanks) break;
      final r = p ~/ cfg.size, c = p % cfg.size;
      final saved = givens[r][c];
      givens[r][c] = 0;
      if (_countSolutions(givens, cfg, limit: 2) == 1) {
        removed++;
      } else {
        givens[r][c] = saved;
      }
    }

    return MiniSudokuBoard(
      cells: [
        for (var r = 0; r < cfg.size; r++)
          [
            for (var c = 0; c < cfg.size; c++)
              SudokuCell(solution[r][c], given: givens[r][c] != 0)
          ]
      ],
      boxRows: cfg.boxRows,
      boxCols: cfg.boxCols,
    );
  }

  /// Fills a complete valid grid by backtracking with shuffled candidates.
  static List<List<int>>? _fillGrid(MiniSudokuConfig cfg, Random rng) {
    final n = cfg.size;
    final grid = List.generate(n, (_) => List<int>.filled(n, 0));

    bool ok(int r, int c, int v) {
      for (var i = 0; i < n; i++) {
        if (grid[r][i] == v || grid[i][c] == v) return false;
      }
      final br = (r ~/ cfg.boxRows) * cfg.boxRows;
      final bc = (c ~/ cfg.boxCols) * cfg.boxCols;
      for (var i = br; i < br + cfg.boxRows; i++) {
        for (var j = bc; j < bc + cfg.boxCols; j++) {
          if (grid[i][j] == v) return false;
        }
      }
      return true;
    }

    bool solve(int pos) {
      if (pos == n * n) return true;
      final r = pos ~/ n, c = pos % n;
      final values = [for (var v = 1; v <= n; v++) v]..shuffle(rng);
      for (final v in values) {
        if (ok(r, c, v)) {
          grid[r][c] = v;
          if (solve(pos + 1)) return true;
          grid[r][c] = 0;
        }
      }
      return false;
    }

    return solve(0) ? grid : null;
  }

  /// Counts solutions of a partial grid, stopping at [limit].
  static int _countSolutions(List<List<int>> givens, MiniSudokuConfig cfg,
      {required int limit}) {
    final n = cfg.size;
    final grid = [
      for (final row in givens) [...row]
    ];
    var count = 0;

    bool ok(int r, int c, int v) {
      for (var i = 0; i < n; i++) {
        if (grid[r][i] == v || grid[i][c] == v) return false;
      }
      final br = (r ~/ cfg.boxRows) * cfg.boxRows;
      final bc = (c ~/ cfg.boxCols) * cfg.boxCols;
      for (var i = br; i < br + cfg.boxRows; i++) {
        for (var j = bc; j < bc + cfg.boxCols; j++) {
          if (grid[i][j] == v) return false;
        }
      }
      return true;
    }

    void solve(int pos) {
      if (count >= limit) return;
      if (pos == n * n) {
        count++;
        return;
      }
      final r = pos ~/ n, c = pos % n;
      if (grid[r][c] != 0) {
        solve(pos + 1);
        return;
      }
      for (var v = 1; v <= n; v++) {
        if (ok(r, c, v)) {
          grid[r][c] = v;
          solve(pos + 1);
          grid[r][c] = 0;
          if (count >= limit) return;
        }
      }
    }

    solve(0);
    return count;
  }
}
